version: "3.7"

services:
  ilovedotnet:
    image: ilovedotnet
    build:
      context: .
      dockerfile: SummHub/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

